namespace MultiplayerInfrastructure.Scenario
{
  public enum ScenarioNodeType
  {
    Dialogue,
    Choice,
    Sound,
    PlayerMove,
    NPCMove,
    CameraTarget,
    Parallel,
    InvokeEvent,
    ServerInternalSignal,
    Validator,
    QuestControl,
    QuestWaypointHighlight,
    Delay,
    Interaction,
    CombineItem,
    Quiz,
    StateUpdate,
    PlayTTS,
    PlayerTag,
    EntityPresetSpawn,
    EntityTag,
    EntityInit,
    TriageAssessControl,
    PatientMedicalStatePreset,
    ItemSubmissionConfig,
    NpcInteractControl,
    ChatPrint,
    ExecuteCommand,
  }
}
